channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - faiss-gpu
  - pip
  - pip:
    - datasets==3.2.0
    - torch==2.5.1
    - transformers==4.47.1
    - tensorboard
    - wandb
    - scipy
    - bert_score